-- Psycopg named placeholders show the exact mapping from universe.csv to SQL columns.
INSERT INTO corpus.company (
    corp_code,
    stock_code,
    corp_name,
    listed_name,
    corp_eng_name,
    market,
    industry,
    sector_no,
    sector,
    listing_date,
    fiscal_month,
    market_cap,
    n_periodic,
    n_major,
    n_exchange,
    n_holding,
    note
) VALUES (
    %(corp_code)s,
    %(stock_code)s,
    %(corp_name)s,
    %(listed_name)s,
    %(corp_eng_name)s,
    %(market)s,
    %(industry)s,
    %(sector_no)s,
    %(sector)s,
    %(listing_date)s,
    %(fiscal_month)s,
    %(market_cap)s,
    %(n_periodic)s,
    %(n_major)s,
    %(n_exchange)s,
    %(n_holding)s,
    %(note)s
)
ON CONFLICT (corp_code) DO UPDATE SET
    stock_code = EXCLUDED.stock_code,
    corp_name = EXCLUDED.corp_name,
    listed_name = EXCLUDED.listed_name,
    corp_eng_name = EXCLUDED.corp_eng_name,
    market = EXCLUDED.market,
    industry = EXCLUDED.industry,
    sector_no = EXCLUDED.sector_no,
    sector = EXCLUDED.sector,
    listing_date = EXCLUDED.listing_date,
    fiscal_month = EXCLUDED.fiscal_month,
    market_cap = EXCLUDED.market_cap,
    n_periodic = EXCLUDED.n_periodic,
    n_major = EXCLUDED.n_major,
    n_exchange = EXCLUDED.n_exchange,
    n_holding = EXCLUDED.n_holding,
    note = EXCLUDED.note;
