INSERT INTO corpus.document_grain (
    grain_id,
    doc_id,
    artifact_id,
    ordinal,
    kind,
    schema_version,
    compiler_version,
    core_text,
    rendered_text,
    estimated_tokens,
    semantic_context,
    source_address,
    previous_grain_id,
    next_grain_id,
    compiled_at
) VALUES (
    %(grain_id)s,
    %(doc_id)s,
    %(artifact_id)s,
    %(ordinal)s,
    %(kind)s,
    %(schema_version)s,
    %(compiler_version)s,
    %(core_text)s,
    %(rendered_text)s,
    %(estimated_tokens)s,
    %(semantic_context_json)s::jsonb,
    %(source_address_json)s::jsonb,
    %(previous_grain_id)s,
    %(next_grain_id)s,
    now()
)
ON CONFLICT (grain_id) DO UPDATE SET
    doc_id = EXCLUDED.doc_id,
    artifact_id = EXCLUDED.artifact_id,
    ordinal = EXCLUDED.ordinal,
    kind = EXCLUDED.kind,
    schema_version = EXCLUDED.schema_version,
    compiler_version = EXCLUDED.compiler_version,
    core_text = EXCLUDED.core_text,
    rendered_text = EXCLUDED.rendered_text,
    estimated_tokens = EXCLUDED.estimated_tokens,
    semantic_context = EXCLUDED.semantic_context,
    source_address = EXCLUDED.source_address,
    previous_grain_id = EXCLUDED.previous_grain_id,
    next_grain_id = EXCLUDED.next_grain_id,
    compiled_at = EXCLUDED.compiled_at;
